app1/urls.py
from django.contrib import admin
from django.urls import path , include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from cours.views import (
   home_screen_view ,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('app01.urls'), name="home"),
    path('cours/', include('cours.urls', 'cours')),
    path('register/',registration_view, name='register'),
    path('logout/',logout_view, name="logout"),
    path('login/',login_view, name="login"),
    path('account/', account_view, name="account"),
    path('cours/', home_screen_view, name="cours"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
     path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_complete'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cours/urls.py
from django.urls import path
from cours.views import (
	create_cours_view,
	detail_cours_view,
)

app_name = 'cours'

urlpatterns = [
    path('create/', create_cours_view, name="create"),
    path('<slug>/', detail_cours_view, name="detail"),
 ]

cours/models.py

from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver

def upload_location(instance, filename):
	file_path = 'cours/{author_id}/{title}-{filename}'.format(
				author_id=str(instance.author.id),title=str(instance.title), filename=filename)
	return file_path

class categories(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=10)
    def str(self):
        return f"{self.title}"

class cours(models.Model):
    title 					= models.CharField(max_length=50, null=False, blank=False)
    body 					= models.TextField(max_length=10000, null=False, blank=False)
    image		 			= models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated 			= models.DateTimeField(auto_now=True, verbose_name="date updated")
    author				= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug 					= models.SlugField(blank=True, unique=True)
    category = models.ForeignKey(categories, on_delete=models.CASCADE)
    def __str__(self):
        return self.title


@receiver(post_delete, sender=cours)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=cours)

cours/forms.py
from django import forms

from cours.models import cours 


class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = cours
		fields = ['title', 'body', 'image', 'category']

cours/views.py

from django.http import HttpResponseRedirect
from django.shortcuts import render ,redirect , get_object_or_404
from cours.models import cours , categories
from cours.forms import CreateBlogPostForm
from account.models import Account
from operator import attrgetter
from django.db.models import Q









def create_cours_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(email=request.user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()

    cat = categories.objects.all()
    context['form'] = form
    context['cat'] = cat

    return render(request, 'cours/create.html', context)
def detail_cours_view(request, slug):
	
	context = {}
	cour_s = get_object_or_404(cours, slug=slug)
	context['cour_s'] = cour_s

	return render(request, 'cours/detail.html', context)

def home_screen_view(request):
	
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    query = ""
    if request.GET:
        query = request.GET['q']
        context['query'] = str(query)
    cour_s = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
    context['cour_s'] = cour_s
    return render(request, "cours/cours.html", context)

def get_blog_queryset(query=None):
	queryset = []
	queries = query.split(" ")
	for q in queries:
		posts = cours.objects.filter(
			Q(title__contains=q)|
			Q(body__icontains=q)|
			Q(category__title__icontains=q)
			).distinct()
		for post in posts:
			queryset.append(post)

	# create unique set and then convert to list
	return list(set(queryset)) 

templates/cours/cours.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					
					<p class="lead">Bienvenue sur notre site d'éducation, où vous pouvez accéder à une vaste gamme de cours et de ressources pédagogiques pour enrichir vos connaissances et développer vos compétences.</p>
					{% if user.is_staff %}<p class="m-auto"><a class="btn btn-primary" href="{% url 'cours:create' %}">Create cours</a></p>{% endif %}
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if cour_s %}
			{% for post in cour_s %}
				<div class="blog-post-container">
					{% include 'cours/snippet.html' with cour_s=post %}
				</div>
			{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'cours/snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->
		</div>
		<!-- end blog feed -->


		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				
				<p class="lead">Bienvenue sur notre site d'éducation, où vous pouvez accéder à une vaste gamme de cours et de ressources pédagogiques pour enrichir vos connaissances et développer vos compétences.</p>
				{% if user.is_staff %}<p class="m-auto"><a class="btn btn-primary" href="{% url 'cours:create' %}">Create cours</a></p>{% endif %}
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->

	</div>
</div>

{% endblock content %}




templates/cours/create.html
{% include 'header.html' %}

{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

				<!-- title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>
				</div>

				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="This cours is about..." required></textarea>
				</div>

				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input  type="file" name="image" id="id_image" accept="image/*" required>
				</div>
				<div class="form-group">
                    <label for="id_category">Category</label>
                    <select class="form-control" name="category" id="id_category" required>
                        {% for opt in cat %}
                        <option value="{{opt.id}}">{{opt.title}}</option>
                        {% endfor %}
                    </select>
                </div>
				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
			</form>	
		</div>
	</div>
</div>




{% endblock content %}

templates/cours/detail.html
{% extends 'base.html' %}


{% block content %}
<style type="text/css">
	.card{
		max-width: 700px;
	}
	.container{
		padding:20px;
	}
</style>

<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<img class="card-img-top" src="{{cour_s.image.url}}">
			<div class="card-body mt-2 mb-2">
			  <h2 class="card-title">{{cour_s.title}}</h2>
			  <p class="card-text">{{cour_s.body|safe}}</p>
			</div>
			<div class="card-footer text-muted">
			  Posted on {{cour_s.date_published}} by {{cour_s.author}}
			</div>
		</div>

	</div>
</div>

	

{% endblock content %}



templates/cours/snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
	}
</style>
{% if cour_s %}
<div class="container">
	<div class="row">

		<!-- Blog Post -->
		<div class="card m-auto">
			<a href="{% url 'cours:detail' post.slug %}">
				<img class="card-img-top" src="{{cour_s.image.url}}">
			</a>
			
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'cours:detail' post.slug %}">
					<h2 class="card-title">{{cour_s.title}}</h2>
				</a>
				<p class="card-text">{{cour_s.body|safe|truncatechars:180}}</p>
				
			</div>
			<div class="card-footer text-muted">
			  Category : {{cour_s.category.title}} - Updated on {{cour_s.date_updated}} by {{cour_s.author}}
			</div>
		</div>
	</div>
</div>
{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">No results</h2>
				<p class="card-text">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}